Messenger/Models/MessageVm.cs
using System.Collections.Generic;

namespace Messenger.Models
{
    public class MessageVm
    {
        public string Url { get; set; }
        public string Text { get; set; }
        public string Subject { get; set; }
        public IEnumerable<string> RecipientsIds { get; set; } = new List<string>();
    }
}

Messenger/Controllers/MessageController.cs
using MessageService;
using MessageService.Repository;
using Messenger.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Messenger.Controllers
{
    public class MessageController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> Send(MessageVm message)
        {
            //todo:n replace with config value
            if (string.IsNullOrEmpty(message.Url))
            {
                message.Url = "http://localhost:8081/api/message/";
            }

            var response = await PostAsync(
                message.Url,
                new Message
                {
                    Body = message.Text,
                    RecipientsIds = message.RecipientsIds,
                    Subject = message.Subject
                });

            var messageResponseStr = await response.Content.ReadAsStringAsync();
            var messageResponse = JsonConvert.DeserializeObject<Response<MessageResponse>>(messageResponseStr);
            return Json(messageResponse);
        }

        private async Task<HttpResponseMessage> PostAsync(string url, object data)
        {
            var postData = JsonConvert.SerializeObject(data);
            var content = new StringContent(postData, Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                return await client.PostAsync(url, content);
            }
        }
    }
}

Messenger/Views/Message/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Messenger";
}

<div class="row">
    <div class="col-md-12">
        <div class="message-form">
            <div class="form-group">
                <label>Service url</label>
                <input type="text" class="service-url" />
            </div>
            <div class="form-group">
                <label>Recipients</label>
                <input class="magicsearch" id="recipients">
            </div>
            <div class="form-group">
                <label>Subject</label>
                <input type="text" class="subject" />
            </div>
            <div class="form-group">
                <label>Message</label>
                <textarea class="message-text"></textarea>
            </div>
            <div>
                <button class="send-btn btn btn-primary">Send</button>
            </div>
        </div>
    </div>
    <div>
        <label class="resp-text"></label>
    </div>
</div>

@section Scripts {
    <script src="~/Scripts/jquery.magicsearch.min.js"></script>
    <script src="~/Scripts/messenger.js"></script>
}

Messenger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/jquery.magicsearch.css" rel="stylesheet">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Messenger", "Index", "Message", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>